url: "https://www.tiny.cloud"
permalink: pretty
origin: "https://www.tiny.cloud"
baseurl: ""
shared_baseurl: ""
syntax_highlight_theme: "tomorrow-night"
cdnurl: "https://cdn.tiny.cloud/1/no-api-key/tinymce/4/tinymce.min.js"
default_meta_keywords: tinymce, documentation, docs, plugins, customizable skins, configuration, examples, html, php, java, javascript, image editor, inline editor, distraction-free editor, classic editor

homepage: "https://www.tiny.cloud/"
pricingpage: "https://www.tiny.cloud/pricing/"
get-tiny: "https://www.tiny.cloud/get-tiny/"
blog: "https://www.tiny.cloud/blog/"
tinymce_fiddle: "https://fiddle.tiny.cloud/"
skintool: "http://skin.tiny.cloud/t4/"

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - wercker.yml
  - node_modules
  - .idea
  - .git
  - .github

markdown: redcarpet

redcarpet:
  extensions:
    - autolink
    - no_intra_emphasis
    - tables
    - prettify

plugins:
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-sitemap
